SC-18 # Allow customers to configure CORS headers
blinkmobile/server-cli pull request #17
Opened 2016-10-21 03:16 UTC by mymattcarroll

### Added

- SC-24: CORS to `bm server serverless` when generating a serverless project

- SC-24: CORS to `bm server serve` when locally hosting routes

   - Will still run if CORS is not setup, and will use [hapi](http://hapijs.com/api#route-options) defaults

- SC-24: Display of CORS for `bm server info` cmd

### Code Review Notes

- Probably worth reviewing these one commit at a time

- Known incomplete work to be tackled in future:

    - [ ] Monitor this [serverless issue](https://github.com/serverless/serverless/issues/2476) and ensure the `bm server serverless` cmd is compatible with the fix

2016-10-21 05:40 UTC, jokeyrhyme requested changes

2016-10-21 05:40 UTC, jokeyrhyme commented on test/cors/read.js
> +test('Should handle an unitinitalised config file', (t) => {
"unitinitalised" typo?

2016-10-21 05:40 UTC, jokeyrhyme commented on lib/cors/validate.js
> +    return Promise.reject(new Error('Must specify cors configuration' + HELP))
It should be okay to not have a CORS configuration. After all, that's what machine-to-machine or Lambda-inception use cases, or even just the common case of native-only front-ends will be likely to do.

2016-10-21 05:40 UTC, jokeyrhyme commented on lib/cors/validate.js
> +    return Promise.reject(new Error('Must specify at least a single allowable origin in cors configuration' + HELP))
You should be allowed to have either 0 origins, or 1 origin, due to the limitations we've discovered with AWS Lambda and/or Serverless.

Once that's been sorted out, we can allow multiple origins.

2016-10-21 05:40 UTC, jokeyrhyme commented on lib/cors/validate.js
> +    return Promise.reject(new Error('Must specify at least a single allowable origin in cors configuration' + HELP))
So, they should be a good production origin in, which we use for production deployments. And we automatically just use "*" for the local development server (if they've specified an origin for production) just to regain some symmetry.

2016-10-21 05:40 UTC, jokeyrhyme commented on lib/serve.js
> +      origin: options.cors.origins,
We have options here, either copy the single origin that they want to use for production, or use the presence of a single origin to decide to use a "*". If they've got no origins, then our local server probably shouldn't either.

2016-10-21 05:44 UTC, mymattcarroll commented on test/cors/read.js
> +test('Should handle an unitinitalised config file', (t) => {
dam

2016-10-21 06:01 UTC, mymattcarroll commented
@jokeyrhyme, what about adding a flag `--no-cors` flag to the `info` (and eventually the `deploy`) cmd to allow you run them without cors configuration set up?

2016-10-21 06:02 UTC, mymattcarroll commented on lib/serve.js
> +      origin: options.cors.origins,
The `serve` cmd already allows for this.

2016-10-24 05:30 UTC, jokeyrhyme commented
@mymattcarroll it will be a very common case to not have CORS configured. I fear hiding this behind a flag would just end up in a similar situation to the `--force` flag that we recently improved.

2016-10-28 00:40 UTC, closed without merging